name: flask-helloworld
on:
  push:
    branches: [ master ]
jobs:
      
  build_docker:
    runs-on: self-hosted
    steps:
      - name: demo
        run: |
          cd /home/test/Desktop/
          pwd
          ls -la
          git clone https://github.com/AnhMD98/TestCIPython
          ping -c 5 8.8.8.8
          pwd
          docker ps -a
          docker ps -a -q
          docker images
          docker container ls
      
