name: flask-helloworld
on:
  release:
    types: [published]
jobs:
      
  build_docker:
    runs-on: self-hosted
    steps:
      - name: demo
        run: |
          cd /home/sysadmin
          pwd
          rm -rf TestCIPython
          docker ps -a
          docker images
          git clone https://github.com/AnhMD98/TestCIPython
          ls -la
          cd /home/sysadmin/TestCIPython/
          ls -la
          
          
        
          
          
      
