name: flask-helloworld
on:
  push:
    branches: [ master ]
jobs:
      
  build_docker:
    runs-on: self-hosted
    steps:
      - name: demo
        run: |
          cd /home/demo
          pwd
          rm -rf TestCIPython
          docker ps -a
          docker images
          docker container stop $(docker ps -a -q)
          docker container rm $(docker ps -a -q)
          docker image rm $(docker images -a)
          git clone https://github.com/AnhMD98/TestCIPython
          ls -la
          cd /home/demo/TestCIPython/
          ls -la
          docker-compose up -d
          docker ps 
          
          
        
          
          
      
